### PR TITLE
Fix test suite to expect 4 spaces.

### LINKED ISSUE #1: Fix the test suite
Right now, the test suite is expecting everything to have 2 space indentation.

Reformatting it to have 4 space indentation would be great! Then we could publish to `stackage`.

### PR DESCRIPTION
**Pull request by georgefst**
(Almost) closes #1.

For reference, this is just the result of running:

``` haskell
#!/usr/bin/env cabal

{- cabal:
build-depends: base,turtle
-}

{-# LANGUAGE OverloadedStrings #-}

import Prelude hiding (FilePath)

import Control.Monad
import Data.Either (fromRight)
import Turtle ((<.>), (</>), FilePath)
import qualified Turtle
import Turtle.Pattern
import Turtle.Prelude
import Turtle.Shell


main = do

    -- remove all output files
    sh $ rm =<< find (suffix "-out.hs") examplesDir

    -- generate new ones
    sh $ do
        inF <- find (suffix ".hs") examplesDir
        let dir = Turtle.directory inF
            base = toText' $ Turtle.basename inF
            outF = dir </> (Turtle.fromText $ base <> "-out") <.> "hs"
        formatted <- snd <$> procStrict "fourmolu" [toText' inF] Turtle.empty
        liftIO $ writeTextFile outF formatted

    where
        toText' = fromRight (error "invalid path encoding") . Turtle.toText

examplesDir = "fourmolu/data/examples"
```

Although I'm sure this is a bash one liner for anyone so inclined, and to be honest, typed filepaths kind of just get in the way here.

### CODE REVIEW

**Comment by georgefst** [comment]
Indeed now that I think about it, it would have been easier to just hack the test script.

But anyway, really I just wanted to get my name on this project, which is to my mind the most important development in Haskell since monadic IO.

**Comment by parsonsmatt** [comment]
image

**Comment by parsonsmatt** [comment]
@georgefst You want commit rights on the repo? :smile:

**Comment by georgefst** [comment]
It would be an honour.

**Pull request merged**
